// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: playback.proto

package info.anodsplace.headunit.aap.protocol.proto;

public final class MediaPlayback {
  private MediaPlayback() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code info.anodsplace.headunit.aap.protocol.proto.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MSG_PLAYBACK_METADATA = 32769;</code>
     */
    MSG_PLAYBACK_METADATA(32769),
    /**
     * <code>MSG_PLAYBACK_STARTRESPONSE = 32770;</code>
     */
    MSG_PLAYBACK_STARTRESPONSE(32770),
    /**
     * <code>MSG_PLAYBACK_METADATASTART = 32771;</code>
     */
    MSG_PLAYBACK_METADATASTART(32771),
    ;

    /**
     * <code>MSG_PLAYBACK_METADATA = 32769;</code>
     */
    public static final int MSG_PLAYBACK_METADATA_VALUE = 32769;
    /**
     * <code>MSG_PLAYBACK_STARTRESPONSE = 32770;</code>
     */
    public static final int MSG_PLAYBACK_STARTRESPONSE_VALUE = 32770;
    /**
     * <code>MSG_PLAYBACK_METADATASTART = 32771;</code>
     */
    public static final int MSG_PLAYBACK_METADATASTART_VALUE = 32771;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    public static MsgType forNumber(int value) {
      switch (value) {
        case 32769: return MSG_PLAYBACK_METADATA;
        case 32770: return MSG_PLAYBACK_STARTRESPONSE;
        case 32771: return MSG_PLAYBACK_METADATASTART;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:info.anodsplace.headunit.aap.protocol.proto.MsgType)
  }

  public interface MediaPlaybackStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus.State state = 1;</code>
     */
    boolean hasState();
    /**
     * <code>optional .info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus.State state = 1;</code>
     */
    info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.State getState();

    /**
     * <code>optional string source = 2;</code>
     */
    boolean hasSource();
    /**
     * <code>optional string source = 2;</code>
     */
    java.lang.String getSource();
    /**
     * <code>optional string source = 2;</code>
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    /**
     * <code>optional uint32 seconds = 3;</code>
     */
    boolean hasSeconds();
    /**
     * <code>optional uint32 seconds = 3;</code>
     */
    int getSeconds();

    /**
     * <code>optional bool shuffle = 4;</code>
     */
    boolean hasShuffle();
    /**
     * <code>optional bool shuffle = 4;</code>
     */
    boolean getShuffle();

    /**
     * <code>optional bool repeat = 5;</code>
     */
    boolean hasRepeat();
    /**
     * <code>optional bool repeat = 5;</code>
     */
    boolean getRepeat();

    /**
     * <code>optional bool repeat_one = 6;</code>
     */
    boolean hasRepeatOne();
    /**
     * <code>optional bool repeat_one = 6;</code>
     */
    boolean getRepeatOne();
  }
  /**
   * Protobuf type {@code info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus}
   */
  public  static final class MediaPlaybackStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus)
      MediaPlaybackStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MediaPlaybackStatus.newBuilder() to construct.
    private MediaPlaybackStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MediaPlaybackStatus() {
      state_ = 0;
      source_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MediaPlaybackStatus();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MediaPlaybackStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.State value = info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.State.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                state_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              source_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              seconds_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              shuffle_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              repeat_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              repeatOne_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaPlaybackStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaPlaybackStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.class, info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.Builder.class);
    }

    /**
     * Protobuf enum {@code info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus.State}
     */
    public enum State
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MEDIA_SERVICE_STATE_PAUSE = 0;</code>
       */
      MEDIA_SERVICE_STATE_PAUSE(0),
      /**
       * <code>MEDIA_SERVICE_STATE_STOPPED = 1;</code>
       */
      MEDIA_SERVICE_STATE_STOPPED(1),
      /**
       * <code>MEDIA_SERVICE_STATE_PLAYING = 3;</code>
       */
      MEDIA_SERVICE_STATE_PLAYING(3),
      ;

      /**
       * <code>MEDIA_SERVICE_STATE_PAUSE = 0;</code>
       */
      public static final int MEDIA_SERVICE_STATE_PAUSE_VALUE = 0;
      /**
       * <code>MEDIA_SERVICE_STATE_STOPPED = 1;</code>
       */
      public static final int MEDIA_SERVICE_STATE_STOPPED_VALUE = 1;
      /**
       * <code>MEDIA_SERVICE_STATE_PLAYING = 3;</code>
       */
      public static final int MEDIA_SERVICE_STATE_PLAYING_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static State valueOf(int value) {
        return forNumber(value);
      }

      public static State forNumber(int value) {
        switch (value) {
          case 0: return MEDIA_SERVICE_STATE_PAUSE;
          case 1: return MEDIA_SERVICE_STATE_STOPPED;
          case 3: return MEDIA_SERVICE_STATE_PLAYING;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<State>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          State> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<State>() {
              public State findValueByNumber(int number) {
                return State.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.getDescriptor().getEnumTypes().get(0);
      }

      private static final State[] VALUES = values();

      public static State valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private State(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus.State)
    }

    private int bitField0_;
    public static final int STATE_FIELD_NUMBER = 1;
    private int state_;
    /**
     * <code>optional .info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus.State state = 1;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus.State state = 1;</code>
     */
    public info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.State getState() {
      @SuppressWarnings("deprecation")
      info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.State result = info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.State.valueOf(state_);
      return result == null ? info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.State.MEDIA_SERVICE_STATE_PAUSE : result;
    }

    public static final int SOURCE_FIELD_NUMBER = 2;
    private volatile java.lang.Object source_;
    /**
     * <code>optional string source = 2;</code>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string source = 2;</code>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          source_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string source = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECONDS_FIELD_NUMBER = 3;
    private int seconds_;
    /**
     * <code>optional uint32 seconds = 3;</code>
     */
    public boolean hasSeconds() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint32 seconds = 3;</code>
     */
    public int getSeconds() {
      return seconds_;
    }

    public static final int SHUFFLE_FIELD_NUMBER = 4;
    private boolean shuffle_;
    /**
     * <code>optional bool shuffle = 4;</code>
     */
    public boolean hasShuffle() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bool shuffle = 4;</code>
     */
    public boolean getShuffle() {
      return shuffle_;
    }

    public static final int REPEAT_FIELD_NUMBER = 5;
    private boolean repeat_;
    /**
     * <code>optional bool repeat = 5;</code>
     */
    public boolean hasRepeat() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional bool repeat = 5;</code>
     */
    public boolean getRepeat() {
      return repeat_;
    }

    public static final int REPEAT_ONE_FIELD_NUMBER = 6;
    private boolean repeatOne_;
    /**
     * <code>optional bool repeat_one = 6;</code>
     */
    public boolean hasRepeatOne() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bool repeat_one = 6;</code>
     */
    public boolean getRepeatOne() {
      return repeatOne_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, state_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, source_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt32(3, seconds_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBool(4, shuffle_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBool(5, repeat_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeBool(6, repeatOne_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, source_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, seconds_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, shuffle_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, repeat_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, repeatOne_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus)) {
        return super.equals(obj);
      }
      info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus other = (info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus) obj;

      if (hasState() != other.hasState()) return false;
      if (hasState()) {
        if (state_ != other.state_) return false;
      }
      if (hasSource() != other.hasSource()) return false;
      if (hasSource()) {
        if (!getSource()
            .equals(other.getSource())) return false;
      }
      if (hasSeconds() != other.hasSeconds()) return false;
      if (hasSeconds()) {
        if (getSeconds()
            != other.getSeconds()) return false;
      }
      if (hasShuffle() != other.hasShuffle()) return false;
      if (hasShuffle()) {
        if (getShuffle()
            != other.getShuffle()) return false;
      }
      if (hasRepeat() != other.hasRepeat()) return false;
      if (hasRepeat()) {
        if (getRepeat()
            != other.getRepeat()) return false;
      }
      if (hasRepeatOne() != other.hasRepeatOne()) return false;
      if (hasRepeatOne()) {
        if (getRepeatOne()
            != other.getRepeatOne()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + state_;
      }
      if (hasSource()) {
        hash = (37 * hash) + SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getSource().hashCode();
      }
      if (hasSeconds()) {
        hash = (37 * hash) + SECONDS_FIELD_NUMBER;
        hash = (53 * hash) + getSeconds();
      }
      if (hasShuffle()) {
        hash = (37 * hash) + SHUFFLE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getShuffle());
      }
      if (hasRepeat()) {
        hash = (37 * hash) + REPEAT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getRepeat());
      }
      if (hasRepeatOne()) {
        hash = (37 * hash) + REPEAT_ONE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getRepeatOne());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus)
        info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaPlaybackStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaPlaybackStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.class, info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.Builder.class);
      }

      // Construct using info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        source_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        seconds_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        shuffle_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        repeat_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        repeatOne_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaPlaybackStatus_descriptor;
      }

      @java.lang.Override
      public info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus getDefaultInstanceForType() {
        return info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.getDefaultInstance();
      }

      @java.lang.Override
      public info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus build() {
        info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus buildPartial() {
        info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus result = new info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.source_ = source_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.seconds_ = seconds_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.shuffle_ = shuffle_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.repeat_ = repeat_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.repeatOne_ = repeatOne_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus) {
          return mergeFrom((info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus other) {
        if (other == info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasSource()) {
          bitField0_ |= 0x00000002;
          source_ = other.source_;
          onChanged();
        }
        if (other.hasSeconds()) {
          setSeconds(other.getSeconds());
        }
        if (other.hasShuffle()) {
          setShuffle(other.getShuffle());
        }
        if (other.hasRepeat()) {
          setRepeat(other.getRepeat());
        }
        if (other.hasRepeatOne()) {
          setRepeatOne(other.getRepeatOne());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int state_ = 0;
      /**
       * <code>optional .info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus.State state = 1;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus.State state = 1;</code>
       */
      public info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.State getState() {
        @SuppressWarnings("deprecation")
        info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.State result = info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.State.valueOf(state_);
        return result == null ? info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.State.MEDIA_SERVICE_STATE_PAUSE : result;
      }
      /**
       * <code>optional .info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus.State state = 1;</code>
       */
      public Builder setState(info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus.State value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus.State state = 1;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object source_ = "";
      /**
       * <code>optional string source = 2;</code>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string source = 2;</code>
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            source_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string source = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string source = 2;</code>
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 2;</code>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000002);
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>optional string source = 2;</code>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        source_ = value;
        onChanged();
        return this;
      }

      private int seconds_ ;
      /**
       * <code>optional uint32 seconds = 3;</code>
       */
      public boolean hasSeconds() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional uint32 seconds = 3;</code>
       */
      public int getSeconds() {
        return seconds_;
      }
      /**
       * <code>optional uint32 seconds = 3;</code>
       */
      public Builder setSeconds(int value) {
        bitField0_ |= 0x00000004;
        seconds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 seconds = 3;</code>
       */
      public Builder clearSeconds() {
        bitField0_ = (bitField0_ & ~0x00000004);
        seconds_ = 0;
        onChanged();
        return this;
      }

      private boolean shuffle_ ;
      /**
       * <code>optional bool shuffle = 4;</code>
       */
      public boolean hasShuffle() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bool shuffle = 4;</code>
       */
      public boolean getShuffle() {
        return shuffle_;
      }
      /**
       * <code>optional bool shuffle = 4;</code>
       */
      public Builder setShuffle(boolean value) {
        bitField0_ |= 0x00000008;
        shuffle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool shuffle = 4;</code>
       */
      public Builder clearShuffle() {
        bitField0_ = (bitField0_ & ~0x00000008);
        shuffle_ = false;
        onChanged();
        return this;
      }

      private boolean repeat_ ;
      /**
       * <code>optional bool repeat = 5;</code>
       */
      public boolean hasRepeat() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional bool repeat = 5;</code>
       */
      public boolean getRepeat() {
        return repeat_;
      }
      /**
       * <code>optional bool repeat = 5;</code>
       */
      public Builder setRepeat(boolean value) {
        bitField0_ |= 0x00000010;
        repeat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool repeat = 5;</code>
       */
      public Builder clearRepeat() {
        bitField0_ = (bitField0_ & ~0x00000010);
        repeat_ = false;
        onChanged();
        return this;
      }

      private boolean repeatOne_ ;
      /**
       * <code>optional bool repeat_one = 6;</code>
       */
      public boolean hasRepeatOne() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional bool repeat_one = 6;</code>
       */
      public boolean getRepeatOne() {
        return repeatOne_;
      }
      /**
       * <code>optional bool repeat_one = 6;</code>
       */
      public Builder setRepeatOne(boolean value) {
        bitField0_ |= 0x00000020;
        repeatOne_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool repeat_one = 6;</code>
       */
      public Builder clearRepeatOne() {
        bitField0_ = (bitField0_ & ~0x00000020);
        repeatOne_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus)
    }

    // @@protoc_insertion_point(class_scope:info.anodsplace.headunit.aap.protocol.proto.MediaPlaybackStatus)
    private static final info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus();
    }

    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MediaPlaybackStatus>
        PARSER = new com.google.protobuf.AbstractParser<MediaPlaybackStatus>() {
      @java.lang.Override
      public MediaPlaybackStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MediaPlaybackStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MediaPlaybackStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MediaPlaybackStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaPlaybackStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MediaMetaDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:info.anodsplace.headunit.aap.protocol.proto.MediaMetaData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string song = 1;</code>
     */
    boolean hasSong();
    /**
     * <code>optional string song = 1;</code>
     */
    java.lang.String getSong();
    /**
     * <code>optional string song = 1;</code>
     */
    com.google.protobuf.ByteString
        getSongBytes();

    /**
     * <code>optional string artist = 2;</code>
     */
    boolean hasArtist();
    /**
     * <code>optional string artist = 2;</code>
     */
    java.lang.String getArtist();
    /**
     * <code>optional string artist = 2;</code>
     */
    com.google.protobuf.ByteString
        getArtistBytes();

    /**
     * <code>optional string album = 3;</code>
     */
    boolean hasAlbum();
    /**
     * <code>optional string album = 3;</code>
     */
    java.lang.String getAlbum();
    /**
     * <code>optional string album = 3;</code>
     */
    com.google.protobuf.ByteString
        getAlbumBytes();

    /**
     * <code>optional bytes albumart = 4;</code>
     */
    boolean hasAlbumart();
    /**
     * <code>optional bytes albumart = 4;</code>
     */
    com.google.protobuf.ByteString getAlbumart();

    /**
     * <code>optional string playlist = 5;</code>
     */
    boolean hasPlaylist();
    /**
     * <code>optional string playlist = 5;</code>
     */
    java.lang.String getPlaylist();
    /**
     * <code>optional string playlist = 5;</code>
     */
    com.google.protobuf.ByteString
        getPlaylistBytes();

    /**
     * <code>optional uint32 duration = 6;</code>
     */
    boolean hasDuration();
    /**
     * <code>optional uint32 duration = 6;</code>
     */
    int getDuration();

    /**
     * <code>optional uint32 rating = 7;</code>
     */
    boolean hasRating();
    /**
     * <code>optional uint32 rating = 7;</code>
     */
    int getRating();
  }
  /**
   * Protobuf type {@code info.anodsplace.headunit.aap.protocol.proto.MediaMetaData}
   */
  public  static final class MediaMetaData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:info.anodsplace.headunit.aap.protocol.proto.MediaMetaData)
      MediaMetaDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MediaMetaData.newBuilder() to construct.
    private MediaMetaData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MediaMetaData() {
      song_ = "";
      artist_ = "";
      album_ = "";
      albumart_ = com.google.protobuf.ByteString.EMPTY;
      playlist_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MediaMetaData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MediaMetaData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              song_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              artist_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              album_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              albumart_ = input.readBytes();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              playlist_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              duration_ = input.readUInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              rating_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaMetaData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaMetaData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData.class, info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData.Builder.class);
    }

    private int bitField0_;
    public static final int SONG_FIELD_NUMBER = 1;
    private volatile java.lang.Object song_;
    /**
     * <code>optional string song = 1;</code>
     */
    public boolean hasSong() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string song = 1;</code>
     */
    public java.lang.String getSong() {
      java.lang.Object ref = song_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          song_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string song = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSongBytes() {
      java.lang.Object ref = song_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        song_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARTIST_FIELD_NUMBER = 2;
    private volatile java.lang.Object artist_;
    /**
     * <code>optional string artist = 2;</code>
     */
    public boolean hasArtist() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string artist = 2;</code>
     */
    public java.lang.String getArtist() {
      java.lang.Object ref = artist_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          artist_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string artist = 2;</code>
     */
    public com.google.protobuf.ByteString
        getArtistBytes() {
      java.lang.Object ref = artist_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        artist_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALBUM_FIELD_NUMBER = 3;
    private volatile java.lang.Object album_;
    /**
     * <code>optional string album = 3;</code>
     */
    public boolean hasAlbum() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string album = 3;</code>
     */
    public java.lang.String getAlbum() {
      java.lang.Object ref = album_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          album_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string album = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAlbumBytes() {
      java.lang.Object ref = album_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        album_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALBUMART_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString albumart_;
    /**
     * <code>optional bytes albumart = 4;</code>
     */
    public boolean hasAlbumart() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes albumart = 4;</code>
     */
    public com.google.protobuf.ByteString getAlbumart() {
      return albumart_;
    }

    public static final int PLAYLIST_FIELD_NUMBER = 5;
    private volatile java.lang.Object playlist_;
    /**
     * <code>optional string playlist = 5;</code>
     */
    public boolean hasPlaylist() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string playlist = 5;</code>
     */
    public java.lang.String getPlaylist() {
      java.lang.Object ref = playlist_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          playlist_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string playlist = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPlaylistBytes() {
      java.lang.Object ref = playlist_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playlist_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DURATION_FIELD_NUMBER = 6;
    private int duration_;
    /**
     * <code>optional uint32 duration = 6;</code>
     */
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional uint32 duration = 6;</code>
     */
    public int getDuration() {
      return duration_;
    }

    public static final int RATING_FIELD_NUMBER = 7;
    private int rating_;
    /**
     * <code>optional uint32 rating = 7;</code>
     */
    public boolean hasRating() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional uint32 rating = 7;</code>
     */
    public int getRating() {
      return rating_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, song_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, artist_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, album_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, albumart_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, playlist_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeUInt32(6, duration_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeUInt32(7, rating_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, song_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, artist_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, album_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, albumart_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, playlist_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, duration_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, rating_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData)) {
        return super.equals(obj);
      }
      info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData other = (info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData) obj;

      if (hasSong() != other.hasSong()) return false;
      if (hasSong()) {
        if (!getSong()
            .equals(other.getSong())) return false;
      }
      if (hasArtist() != other.hasArtist()) return false;
      if (hasArtist()) {
        if (!getArtist()
            .equals(other.getArtist())) return false;
      }
      if (hasAlbum() != other.hasAlbum()) return false;
      if (hasAlbum()) {
        if (!getAlbum()
            .equals(other.getAlbum())) return false;
      }
      if (hasAlbumart() != other.hasAlbumart()) return false;
      if (hasAlbumart()) {
        if (!getAlbumart()
            .equals(other.getAlbumart())) return false;
      }
      if (hasPlaylist() != other.hasPlaylist()) return false;
      if (hasPlaylist()) {
        if (!getPlaylist()
            .equals(other.getPlaylist())) return false;
      }
      if (hasDuration() != other.hasDuration()) return false;
      if (hasDuration()) {
        if (getDuration()
            != other.getDuration()) return false;
      }
      if (hasRating() != other.hasRating()) return false;
      if (hasRating()) {
        if (getRating()
            != other.getRating()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSong()) {
        hash = (37 * hash) + SONG_FIELD_NUMBER;
        hash = (53 * hash) + getSong().hashCode();
      }
      if (hasArtist()) {
        hash = (37 * hash) + ARTIST_FIELD_NUMBER;
        hash = (53 * hash) + getArtist().hashCode();
      }
      if (hasAlbum()) {
        hash = (37 * hash) + ALBUM_FIELD_NUMBER;
        hash = (53 * hash) + getAlbum().hashCode();
      }
      if (hasAlbumart()) {
        hash = (37 * hash) + ALBUMART_FIELD_NUMBER;
        hash = (53 * hash) + getAlbumart().hashCode();
      }
      if (hasPlaylist()) {
        hash = (37 * hash) + PLAYLIST_FIELD_NUMBER;
        hash = (53 * hash) + getPlaylist().hashCode();
      }
      if (hasDuration()) {
        hash = (37 * hash) + DURATION_FIELD_NUMBER;
        hash = (53 * hash) + getDuration();
      }
      if (hasRating()) {
        hash = (37 * hash) + RATING_FIELD_NUMBER;
        hash = (53 * hash) + getRating();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code info.anodsplace.headunit.aap.protocol.proto.MediaMetaData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:info.anodsplace.headunit.aap.protocol.proto.MediaMetaData)
        info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaMetaData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaMetaData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData.class, info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData.Builder.class);
      }

      // Construct using info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        song_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        artist_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        album_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        albumart_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        playlist_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        duration_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        rating_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaMetaData_descriptor;
      }

      @java.lang.Override
      public info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData getDefaultInstanceForType() {
        return info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData.getDefaultInstance();
      }

      @java.lang.Override
      public info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData build() {
        info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData buildPartial() {
        info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData result = new info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.song_ = song_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.artist_ = artist_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.album_ = album_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.albumart_ = albumart_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.playlist_ = playlist_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.duration_ = duration_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.rating_ = rating_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData) {
          return mergeFrom((info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData other) {
        if (other == info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData.getDefaultInstance()) return this;
        if (other.hasSong()) {
          bitField0_ |= 0x00000001;
          song_ = other.song_;
          onChanged();
        }
        if (other.hasArtist()) {
          bitField0_ |= 0x00000002;
          artist_ = other.artist_;
          onChanged();
        }
        if (other.hasAlbum()) {
          bitField0_ |= 0x00000004;
          album_ = other.album_;
          onChanged();
        }
        if (other.hasAlbumart()) {
          setAlbumart(other.getAlbumart());
        }
        if (other.hasPlaylist()) {
          bitField0_ |= 0x00000010;
          playlist_ = other.playlist_;
          onChanged();
        }
        if (other.hasDuration()) {
          setDuration(other.getDuration());
        }
        if (other.hasRating()) {
          setRating(other.getRating());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object song_ = "";
      /**
       * <code>optional string song = 1;</code>
       */
      public boolean hasSong() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string song = 1;</code>
       */
      public java.lang.String getSong() {
        java.lang.Object ref = song_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            song_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string song = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSongBytes() {
        java.lang.Object ref = song_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          song_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string song = 1;</code>
       */
      public Builder setSong(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        song_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string song = 1;</code>
       */
      public Builder clearSong() {
        bitField0_ = (bitField0_ & ~0x00000001);
        song_ = getDefaultInstance().getSong();
        onChanged();
        return this;
      }
      /**
       * <code>optional string song = 1;</code>
       */
      public Builder setSongBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        song_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object artist_ = "";
      /**
       * <code>optional string artist = 2;</code>
       */
      public boolean hasArtist() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string artist = 2;</code>
       */
      public java.lang.String getArtist() {
        java.lang.Object ref = artist_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            artist_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string artist = 2;</code>
       */
      public com.google.protobuf.ByteString
          getArtistBytes() {
        java.lang.Object ref = artist_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          artist_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string artist = 2;</code>
       */
      public Builder setArtist(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        artist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string artist = 2;</code>
       */
      public Builder clearArtist() {
        bitField0_ = (bitField0_ & ~0x00000002);
        artist_ = getDefaultInstance().getArtist();
        onChanged();
        return this;
      }
      /**
       * <code>optional string artist = 2;</code>
       */
      public Builder setArtistBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        artist_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object album_ = "";
      /**
       * <code>optional string album = 3;</code>
       */
      public boolean hasAlbum() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string album = 3;</code>
       */
      public java.lang.String getAlbum() {
        java.lang.Object ref = album_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            album_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string album = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAlbumBytes() {
        java.lang.Object ref = album_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          album_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string album = 3;</code>
       */
      public Builder setAlbum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        album_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string album = 3;</code>
       */
      public Builder clearAlbum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        album_ = getDefaultInstance().getAlbum();
        onChanged();
        return this;
      }
      /**
       * <code>optional string album = 3;</code>
       */
      public Builder setAlbumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        album_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString albumart_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes albumart = 4;</code>
       */
      public boolean hasAlbumart() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bytes albumart = 4;</code>
       */
      public com.google.protobuf.ByteString getAlbumart() {
        return albumart_;
      }
      /**
       * <code>optional bytes albumart = 4;</code>
       */
      public Builder setAlbumart(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        albumart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes albumart = 4;</code>
       */
      public Builder clearAlbumart() {
        bitField0_ = (bitField0_ & ~0x00000008);
        albumart_ = getDefaultInstance().getAlbumart();
        onChanged();
        return this;
      }

      private java.lang.Object playlist_ = "";
      /**
       * <code>optional string playlist = 5;</code>
       */
      public boolean hasPlaylist() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string playlist = 5;</code>
       */
      public java.lang.String getPlaylist() {
        java.lang.Object ref = playlist_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            playlist_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string playlist = 5;</code>
       */
      public com.google.protobuf.ByteString
          getPlaylistBytes() {
        java.lang.Object ref = playlist_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playlist_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string playlist = 5;</code>
       */
      public Builder setPlaylist(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        playlist_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string playlist = 5;</code>
       */
      public Builder clearPlaylist() {
        bitField0_ = (bitField0_ & ~0x00000010);
        playlist_ = getDefaultInstance().getPlaylist();
        onChanged();
        return this;
      }
      /**
       * <code>optional string playlist = 5;</code>
       */
      public Builder setPlaylistBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        playlist_ = value;
        onChanged();
        return this;
      }

      private int duration_ ;
      /**
       * <code>optional uint32 duration = 6;</code>
       */
      public boolean hasDuration() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional uint32 duration = 6;</code>
       */
      public int getDuration() {
        return duration_;
      }
      /**
       * <code>optional uint32 duration = 6;</code>
       */
      public Builder setDuration(int value) {
        bitField0_ |= 0x00000020;
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 duration = 6;</code>
       */
      public Builder clearDuration() {
        bitField0_ = (bitField0_ & ~0x00000020);
        duration_ = 0;
        onChanged();
        return this;
      }

      private int rating_ ;
      /**
       * <code>optional uint32 rating = 7;</code>
       */
      public boolean hasRating() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional uint32 rating = 7;</code>
       */
      public int getRating() {
        return rating_;
      }
      /**
       * <code>optional uint32 rating = 7;</code>
       */
      public Builder setRating(int value) {
        bitField0_ |= 0x00000040;
        rating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 rating = 7;</code>
       */
      public Builder clearRating() {
        bitField0_ = (bitField0_ & ~0x00000040);
        rating_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:info.anodsplace.headunit.aap.protocol.proto.MediaMetaData)
    }

    // @@protoc_insertion_point(class_scope:info.anodsplace.headunit.aap.protocol.proto.MediaMetaData)
    private static final info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData();
    }

    public static info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MediaMetaData>
        PARSER = new com.google.protobuf.AbstractParser<MediaMetaData>() {
      @java.lang.Override
      public MediaMetaData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MediaMetaData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MediaMetaData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MediaMetaData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public info.anodsplace.headunit.aap.protocol.proto.MediaPlayback.MediaMetaData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaPlaybackStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaPlaybackStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaMetaData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaMetaData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016playback.proto\022+info.anodsplace.headun" +
      "it.aap.protocol.proto\"\254\002\n\023MediaPlaybackS" +
      "tatus\022U\n\005state\030\001 \001(\0162F.info.anodsplace.h" +
      "eadunit.aap.protocol.proto.MediaPlayback" +
      "Status.State\022\016\n\006source\030\002 \001(\t\022\017\n\007seconds\030" +
      "\003 \001(\r\022\017\n\007shuffle\030\004 \001(\010\022\016\n\006repeat\030\005 \001(\010\022\022" +
      "\n\nrepeat_one\030\006 \001(\010\"h\n\005State\022\035\n\031MEDIA_SER" +
      "VICE_STATE_PAUSE\020\000\022\037\n\033MEDIA_SERVICE_STAT" +
      "E_STOPPED\020\001\022\037\n\033MEDIA_SERVICE_STATE_PLAYI" +
      "NG\020\003\"\202\001\n\rMediaMetaData\022\014\n\004song\030\001 \001(\t\022\016\n\006" +
      "artist\030\002 \001(\t\022\r\n\005album\030\003 \001(\t\022\020\n\010albumart\030" +
      "\004 \001(\014\022\020\n\010playlist\030\005 \001(\t\022\020\n\010duration\030\006 \001(" +
      "\r\022\016\n\006rating\030\007 \001(\r*j\n\007MsgType\022\033\n\025MSG_PLAY" +
      "BACK_METADATA\020\201\200\002\022 \n\032MSG_PLAYBACK_STARTR" +
      "ESPONSE\020\202\200\002\022 \n\032MSG_PLAYBACK_METADATASTAR" +
      "T\020\203\200\002B\017B\rMediaPlayback"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaPlaybackStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaPlaybackStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaPlaybackStatus_descriptor,
        new java.lang.String[] { "State", "Source", "Seconds", "Shuffle", "Repeat", "RepeatOne", });
    internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaMetaData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaMetaData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_info_anodsplace_headunit_aap_protocol_proto_MediaMetaData_descriptor,
        new java.lang.String[] { "Song", "Artist", "Album", "Albumart", "Playlist", "Duration", "Rating", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
