// Generated by the protocol buffer compiler.  DO NOT EDIT!

package ca.anodsplace.headunit.aap.protocol.nano;

@SuppressWarnings("hiding")
public interface Common {

  // enum MessageStatus
  public static final int STATUS_OK = 0;
}
